package aspects.xpt

import xpt.Common

class CommonExtended extends Common {
	
	override doGeneratedComment(String comment, String comment2) '''
		/** 
		 *	@generated 
		 *	@author generated by aspects.CommonExtended
		 *  3rd line 
		 */
	'''	
}