/**
 * <copyright>
 * </copyright>
 *
 * $Id: MapValidator.java,v 1.1 2007/01/09 17:20:51 rgronback Exp $
 */
package org.eclipse.gmf.examples.mindmap.validation;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link org.eclipse.gmf.examples.mindmap.Map}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MapValidator {
	boolean validate();

	boolean validateRootTopics(EList value);
	boolean validateRelations(EList value);
	boolean validateResources(EList value);
	boolean validateTitle(String value);
}
