/**
 * <copyright>
 * </copyright>
 *
 * $Id: RelationshipValidator.java,v 1.2 2007/01/09 19:02:33 rgronback Exp $
 */
package org.eclipse.gmf.examples.mindmap.validation;

import org.eclipse.gmf.examples.mindmap.RelationshipType;
import org.eclipse.gmf.examples.mindmap.Topic;

/**
 * A sample validator interface for {@link org.eclipse.gmf.examples.mindmap.Relationship}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RelationshipValidator {
	boolean validate();

	boolean validateLabel(String value);
	boolean validateSource(Topic value);
	boolean validateTarget(Topic value);
	boolean validateType(RelationshipType value);
}
