/**
 * <copyright>
 * </copyright>
 *
 * $Id: ResourceValidator.java,v 1.1 2007/01/09 17:20:50 rgronback Exp $
 */
package org.eclipse.gmf.examples.mindmap.validation;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link org.eclipse.gmf.examples.mindmap.Resource}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ResourceValidator {
	boolean validate();

	boolean validateComments(EList value);
	boolean validateEmail(String value);
	boolean validateName(String value);
	boolean validateTopics(EList value);
}
