/**
 * <copyright>
 * </copyright>
 *
 * $Id: ThreadItemValidator.java,v 1.2 2007/01/09 19:02:33 rgronback Exp $
 */
package org.eclipse.gmf.examples.mindmap.validation;

import org.eclipse.gmf.examples.mindmap.Resource;

/**
 * A sample validator interface for {@link org.eclipse.gmf.examples.mindmap.ThreadItem}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ThreadItemValidator {
	boolean validate();

	boolean validateAuthor(Resource value);
	boolean validateBody(String value);
	boolean validateItemPostDate(Object value);
}
