/**
 * <copyright>
 * </copyright>
 *
 * $Id: TopicValidator.java,v 1.2 2007/01/09 19:02:33 rgronback Exp $
 */
package org.eclipse.gmf.examples.mindmap.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.gmf.examples.mindmap.Priority;

/**
 * A sample validator interface for {@link org.eclipse.gmf.examples.mindmap.Topic}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TopicValidator {
	boolean validate();

	boolean validateComments(EList value);
	boolean validateDuration(float value);
	boolean validateEndDate(Object value);
	boolean validateName(String value);
	boolean validatePercentComplete(float value);
	boolean validatePriority(Priority value);
	boolean validateResources(EList value);
	boolean validateStartDate(Object value);
	boolean validateSubtopics(EList value);
}
