/*
 * Copyright (c) 2006, 2009 Borland Software Corporation and others.
 * All rights reserved.   This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     committers of openArchitectureWare - Xpand language syntax
 *     Artem Tikhomirov (Borland) - LALR grammar
 *                                - Migration to OCL expressions
 */
package org.eclipse.gmf.internal.xpand.parser;

public interface XpandParsersym {
    public final static int
      TK_STRING_LITERAL = 36,
      TK_INTEGER_LITERAL = 40,
      TK_REAL_LITERAL = 41,
      TK_PLUS = 57,
      TK_MINUS = 8,
      TK_MULTIPLY = 4,
      TK_DIVIDE = 63,
      TK_GREATER = 58,
      TK_LESS = 59,
      TK_EQUAL = 54,
      TK_GREATER_EQUAL = 60,
      TK_LESS_EQUAL = 61,
      TK_NOT_EQUAL = 66,
      TK_LPAREN = 1,
      TK_RPAREN = 2,
      TK_LBRACE = 64,
      TK_RBRACE = 62,
      TK_LBRACKET = 70,
      TK_RBRACKET = 83,
      TK_ARROW = 42,
      TK_BAR = 52,
      TK_COMMA = 45,
      TK_COLON = 55,
      TK_COLONCOLON = 50,
      TK_SEMICOLON = 71,
      TK_DOT = 43,
      TK_DOTDOT = 84,
      TK_ADD_ASSIGN = 116,
      TK_RESET_ASSIGN = 72,
      TK_AT = 117,
      TK_EXCLAMATION_MARK = 85,
      TK_NOT_EQUAL_EXEQ = 73,
      TK_class = 118,
      TK_composes = 119,
      TK_constructor = 120,
      TK_datatype = 121,
      TK_default = 122,
      TK_derived = 123,
      TK_do = 124,
      TK_elif = 125,
      TK_enum = 126,
      TK_except = 127,
      TK_exception = 128,
      TK_from = 129,
      TK_literal = 130,
      TK_ordered = 131,
      TK_primitive = 132,
      TK_raise = 133,
      TK_readonly = 134,
      TK_references = 135,
      TK_tag = 136,
      TK_try = 137,
      TK_typedef = 138,
      TK_unlimited = 139,
      TK_invalid = 9,
      TK_COLONCOLONEQUAL = 140,
      TK_QUESTIONMARK = 141,
      TK_IMPORT = 86,
      TK_EXTENSION = 87,
      TK_AROUND = 74,
      TK_ENDAROUND = 65,
      TK_DEFINE = 75,
      TK_ENDDEFINE = 76,
      TK_ERROR = 88,
      TK_EXPAND = 89,
      TK_FOR = 56,
      TK_SEPARATOR = 90,
      TK_AS = 77,
      TK_ITERATOR = 91,
      TK_FOREACH = 78,
      TK_ENDFOREACH = 92,
      TK_FILE = 93,
      TK_ENDFILE = 94,
      TK_IF = 95,
      TK_ELSEIF = 96,
      TK_ELSE = 97,
      TK_ENDIF = 98,
      TK_LET = 99,
      TK_ENDLET = 100,
      TK_PROTECT = 101,
      TK_CSTART = 102,
      TK_CEND = 103,
      TK_ID = 104,
      TK_DISABLE = 105,
      TK_ENDPROTECT = 106,
      TK_LG = 107,
      TK_self = 10,
      TK_if = 46,
      TK_then = 108,
      TK_else = 109,
      TK_endif = 79,
      TK_and = 67,
      TK_or = 68,
      TK_xor = 69,
      TK_not = 44,
      TK_implies = 80,
      TK_let = 47,
      TK_in = 81,
      TK_true = 5,
      TK_false = 6,
      TK_null = 7,
      TK_Set = 11,
      TK_Bag = 12,
      TK_Sequence = 13,
      TK_Collection = 14,
      TK_OrderedSet = 15,
      TK_iterate = 16,
      TK_forAll = 17,
      TK_exists = 18,
      TK_isUnique = 19,
      TK_any = 20,
      TK_one = 21,
      TK_collect = 22,
      TK_select = 23,
      TK_reject = 24,
      TK_collectNested = 25,
      TK_sortedBy = 26,
      TK_closure = 27,
      TK_String = 28,
      TK_Integer = 29,
      TK_UnlimitedNatural = 30,
      TK_Real = 31,
      TK_Boolean = 32,
      TK_Tuple = 37,
      TK_OclAny = 33,
      TK_OclVoid = 34,
      TK_OclInvalid = 35,
      TK_inv = 142,
      TK_pre = 143,
      TK_post = 144,
      TK_context = 145,
      TK_package = 146,
      TK_endpackage = 147,
      TK_def = 148,
      TK_body = 149,
      TK_derive = 150,
      TK_init = 151,
      TK_static = 152,
      TK_OclMessage = 153,
      TK_end = 154,
      TK_while = 155,
      TK_out = 156,
      TK_object = 157,
      TK_transformation = 158,
      TK_import = 159,
      TK_library = 160,
      TK_metamodel = 161,
      TK_mapping = 162,
      TK_query = 163,
      TK_helper = 164,
      TK_inout = 165,
      TK_when = 166,
      TK_var = 167,
      TK_configuration = 168,
      TK_intermediate = 169,
      TK_property = 170,
      TK_opposites = 171,
      TK_population = 172,
      TK_map = 173,
      TK_new = 174,
      TK_xmap = 175,
      TK_late = 176,
      TK_log = 177,
      TK_assert = 178,
      TK_with = 179,
      TK_resolve = 180,
      TK_resolveone = 181,
      TK_resolveIn = 182,
      TK_resolveoneIn = 183,
      TK_invresolve = 184,
      TK_invresolveone = 185,
      TK_invresolveIn = 186,
      TK_invresolveoneIn = 187,
      TK_modeltype = 188,
      TK_uses = 189,
      TK_where = 190,
      TK_refines = 191,
      TK_access = 192,
      TK_extends = 193,
      TK_blackbox = 194,
      TK_abstract = 195,
      TK_result = 196,
      TK_main = 197,
      TK_this = 198,
      TK_switch = 199,
      TK_case = 200,
      TK_xselect = 110,
      TK_xcollect = 111,
      TK_selectOne = 112,
      TK_collectOne = 113,
      TK_collectselect = 114,
      TK_collectselectOne = 115,
      TK_return = 201,
      TK_rename = 202,
      TK_disjuncts = 203,
      TK_merges = 204,
      TK_inherits = 205,
      TK_forEach = 206,
      TK_forOne = 207,
      TK_compute = 208,
      TK_Dict = 38,
      TK_List = 39,
      TK_break = 48,
      TK_continue = 49,
      TK_EOF_TOKEN = 82,
      TK_IDENTIFIER = 3,
      TK_SINGLE_LINE_COMMENT = 209,
      TK_MULTI_LINE_COMMENT = 210,
      TK_CARET = 211,
      TK_CARETCARET = 212,
      TK_STEREOTYPE_QUALIFIER_OPEN = 213,
      TK_STEREOTYPE_QUALIFIER_CLOSE = 214,
      TK_MULTIPLICITY_RANGE = 215,
      TK_TILDE_SIGN = 216,
      TK_TEXT = 53,
      TK_ERROR_TOKEN = 51;

      public final static String orderedTerminalSymbols[] = {
                 "",
                 "LPAREN",
                 "RPAREN",
                 "IDENTIFIER",
                 "MULTIPLY",
                 "true",
                 "false",
                 "null",
                 "MINUS",
                 "invalid",
                 "self",
                 "Set",
                 "Bag",
                 "Sequence",
                 "Collection",
                 "OrderedSet",
                 "iterate",
                 "forAll",
                 "exists",
                 "isUnique",
                 "any",
                 "one",
                 "collect",
                 "select",
                 "reject",
                 "collectNested",
                 "sortedBy",
                 "closure",
                 "String",
                 "Integer",
                 "UnlimitedNatural",
                 "Real",
                 "Boolean",
                 "OclAny",
                 "OclVoid",
                 "OclInvalid",
                 "STRING_LITERAL",
                 "Tuple",
                 "Dict",
                 "List",
                 "INTEGER_LITERAL",
                 "REAL_LITERAL",
                 "ARROW",
                 "DOT",
                 "not",
                 "COMMA",
                 "if",
                 "let",
                 "break",
                 "continue",
                 "COLONCOLON",
                 "ERROR_TOKEN",
                 "BAR",
                 "TEXT",
                 "EQUAL",
                 "COLON",
                 "FOR",
                 "PLUS",
                 "GREATER",
                 "LESS",
                 "GREATER_EQUAL",
                 "LESS_EQUAL",
                 "RBRACE",
                 "DIVIDE",
                 "LBRACE",
                 "ENDAROUND",
                 "NOT_EQUAL",
                 "and",
                 "or",
                 "xor",
                 "LBRACKET",
                 "SEMICOLON",
                 "RESET_ASSIGN",
                 "NOT_EQUAL_EXEQ",
                 "AROUND",
                 "DEFINE",
                 "ENDDEFINE",
                 "AS",
                 "FOREACH",
                 "endif",
                 "implies",
                 "in",
                 "EOF_TOKEN",
                 "RBRACKET",
                 "DOTDOT",
                 "EXCLAMATION_MARK",
                 "IMPORT",
                 "EXTENSION",
                 "ERROR",
                 "EXPAND",
                 "SEPARATOR",
                 "ITERATOR",
                 "ENDFOREACH",
                 "FILE",
                 "ENDFILE",
                 "IF",
                 "ELSEIF",
                 "ELSE",
                 "ENDIF",
                 "LET",
                 "ENDLET",
                 "PROTECT",
                 "CSTART",
                 "CEND",
                 "ID",
                 "DISABLE",
                 "ENDPROTECT",
                 "LG",
                 "then",
                 "else",
                 "xselect",
                 "xcollect",
                 "selectOne",
                 "collectOne",
                 "collectselect",
                 "collectselectOne",
                 "ADD_ASSIGN",
                 "AT",
                 "class",
                 "composes",
                 "constructor",
                 "datatype",
                 "default",
                 "derived",
                 "do",
                 "elif",
                 "enum",
                 "except",
                 "exception",
                 "from",
                 "literal",
                 "ordered",
                 "primitive",
                 "raise",
                 "readonly",
                 "references",
                 "tag",
                 "try",
                 "typedef",
                 "unlimited",
                 "COLONCOLONEQUAL",
                 "QUESTIONMARK",
                 "inv",
                 "pre",
                 "post",
                 "context",
                 "package",
                 "endpackage",
                 "def",
                 "body",
                 "derive",
                 "init",
                 "static",
                 "OclMessage",
                 "end",
                 "while",
                 "out",
                 "object",
                 "transformation",
                 "import",
                 "library",
                 "metamodel",
                 "mapping",
                 "query",
                 "helper",
                 "inout",
                 "when",
                 "var",
                 "configuration",
                 "intermediate",
                 "property",
                 "opposites",
                 "population",
                 "map",
                 "new",
                 "xmap",
                 "late",
                 "log",
                 "assert",
                 "with",
                 "resolve",
                 "resolveone",
                 "resolveIn",
                 "resolveoneIn",
                 "invresolve",
                 "invresolveone",
                 "invresolveIn",
                 "invresolveoneIn",
                 "modeltype",
                 "uses",
                 "where",
                 "refines",
                 "access",
                 "extends",
                 "blackbox",
                 "abstract",
                 "result",
                 "main",
                 "this",
                 "switch",
                 "case",
                 "return",
                 "rename",
                 "disjuncts",
                 "merges",
                 "inherits",
                 "forEach",
                 "forOne",
                 "compute",
                 "SINGLE_LINE_COMMENT",
                 "MULTI_LINE_COMMENT",
                 "CARET",
                 "CARETCARET",
                 "STEREOTYPE_QUALIFIER_OPEN",
                 "STEREOTYPE_QUALIFIER_CLOSE",
                 "MULTIPLICITY_RANGE",
                 "TILDE_SIGN"
             };

    public final static boolean isValidForParser = true;
}
