/*
 * Copyright (c) 2006, 2008 Borland Software Corporation and others.
 * All rights reserved.   This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     committers of openArchitectureWare - Xpand language syntax
 *     Artem Tikhomirov (Borland) - LALR grammar
 *                                - Migration to OCL expressions
 */
package org.eclipse.gmf.internal.xpand.parser;

public interface XpandParsersym {
    public final static int
      TK_NUMERIC_OPERATION = 59,
      TK_STRING_LITERAL = 58,
      TK_INTEGER_LITERAL = 60,
      TK_REAL_LITERAL = 61,
      TK_PLUS = 30,
      TK_MINUS = 15,
      TK_MULTIPLY = 5,
      TK_DIVIDE = 26,
      TK_GREATER = 16,
      TK_LESS = 17,
      TK_EQUAL = 4,
      TK_GREATER_EQUAL = 18,
      TK_LESS_EQUAL = 19,
      TK_NOT_EQUAL = 20,
      TK_LPAREN = 1,
      TK_RPAREN = 2,
      TK_LBRACE = 73,
      TK_RBRACE = 82,
      TK_LBRACKET = 74,
      TK_RBRACKET = 78,
      TK_ARROW = 88,
      TK_BAR = 71,
      TK_COMMA = 69,
      TK_COLON = 76,
      TK_COLONCOLON = 72,
      TK_SEMICOLON = 83,
      TK_DOT = 89,
      TK_DOTDOT = 90,
      TK_ATPRE = 79,
      TK_CARET = 91,
      TK_CARETCARET = 92,
      TK_QUESTIONMARK = 93,
      TK_QUOTE_STRING_LITERAL = 107,
      TK_ADD_ASSIGN = 132,
      TK_RESET_ASSIGN = 94,
      TK_AT_SIGN = 133,
      TK_EXCLAMATION_MARK = 80,
      TK_NOT_EQUAL_EXEQ = 77,
      TK_INTEGER_RANGE_START = 84,
      TK_IMPORT = 108,
      TK_EXTENSION = 109,
      TK_AROUND = 95,
      TK_ENDAROUND = 81,
      TK_DEFINE = 96,
      TK_ENDDEFINE = 97,
      TK_ERROR = 110,
      TK_EXPAND = 111,
      TK_FOR = 75,
      TK_SEPARATOR = 98,
      TK_AS = 85,
      TK_ITERATOR = 112,
      TK_FOREACH = 99,
      TK_ENDFOREACH = 113,
      TK_FILE = 114,
      TK_ENDFILE = 115,
      TK_IF = 116,
      TK_ELSEIF = 117,
      TK_ELSE = 118,
      TK_ENDIF = 119,
      TK_LET = 120,
      TK_ENDLET = 121,
      TK_PROTECT = 122,
      TK_CSTART = 123,
      TK_CEND = 100,
      TK_ID = 101,
      TK_DISABLE = 102,
      TK_ENDPROTECT = 124,
      TK_LG = 125,
      TK_self = 31,
      TK_inv = 134,
      TK_pre = 135,
      TK_post = 136,
      TK_context = 137,
      TK_package = 138,
      TK_endpackage = 139,
      TK_def = 140,
      TK_if = 62,
      TK_then = 103,
      TK_else = 104,
      TK_endif = 86,
      TK_and = 27,
      TK_or = 28,
      TK_xor = 29,
      TK_not = 50,
      TK_implies = 105,
      TK_let = 67,
      TK_in = 87,
      TK_true = 63,
      TK_false = 64,
      TK_body = 33,
      TK_derive = 34,
      TK_init = 35,
      TK_null = 36,
      TK_attr = 141,
      TK_oper = 142,
      TK_Set = 21,
      TK_Bag = 22,
      TK_Sequence = 23,
      TK_Collection = 24,
      TK_OrderedSet = 25,
      TK_iterate = 37,
      TK_forAll = 38,
      TK_exists = 39,
      TK_isUnique = 40,
      TK_any = 41,
      TK_one = 42,
      TK_collect = 43,
      TK_select = 44,
      TK_reject = 45,
      TK_collectNested = 46,
      TK_sortedBy = 47,
      TK_closure = 48,
      TK_oclIsKindOf = 51,
      TK_oclIsTypeOf = 52,
      TK_oclAsType = 53,
      TK_oclIsNew = 54,
      TK_oclIsUndefined = 55,
      TK_oclIsInvalid = 56,
      TK_oclIsInState = 57,
      TK_allInstances = 49,
      TK_String = 6,
      TK_Integer = 7,
      TK_UnlimitedNatural = 8,
      TK_Real = 9,
      TK_Boolean = 10,
      TK_Tuple = 32,
      TK_OclAny = 11,
      TK_OclVoid = 12,
      TK_Invalid = 13,
      TK_OclMessage = 14,
      TK_OclInvalid = 65,
      TK_end = 143,
      TK_while = 144,
      TK_out = 145,
      TK_object = 146,
      TK_transformation = 147,
      TK_import = 148,
      TK_library = 149,
      TK_metamodel = 150,
      TK_mapping = 151,
      TK_query = 152,
      TK_helper = 153,
      TK_inout = 154,
      TK_when = 155,
      TK_var = 156,
      TK_configuration = 157,
      TK_intermediate = 158,
      TK_property = 159,
      TK_population = 160,
      TK_map = 161,
      TK_new = 66,
      TK_xmap = 162,
      TK_late = 163,
      TK_log = 164,
      TK_assert = 165,
      TK_with = 166,
      TK_resolve = 167,
      TK_resolveone = 168,
      TK_resolveIn = 169,
      TK_resolveoneIn = 170,
      TK_invresolve = 171,
      TK_invresolveone = 172,
      TK_invresolveIn = 173,
      TK_invresolveoneIn = 174,
      TK_modeltype = 175,
      TK_uses = 176,
      TK_where = 177,
      TK_refines = 178,
      TK_enforcing = 179,
      TK_access = 180,
      TK_extends = 181,
      TK_blackbox = 182,
      TK_abstract = 183,
      TK_static = 184,
      TK_result = 185,
      TK_main = 186,
      TK_this = 187,
      TK_switch = 188,
      TK_case = 189,
      TK_xselect = 126,
      TK_xcollect = 127,
      TK_selectOne = 128,
      TK_collectOne = 129,
      TK_collectselect = 130,
      TK_collectselectOne = 131,
      TK_return = 190,
      TK_rename = 191,
      TK_disjuncts = 192,
      TK_merges = 193,
      TK_inherits = 194,
      TK_forEach = 195,
      TK_forOne = 196,
      TK_compute = 197,
      TK_EOF_TOKEN = 106,
      TK_IDENTIFIER = 3,
      TK_TEXT = 70,
      TK_ERROR_TOKEN = 68;

      public final static String orderedTerminalSymbols[] = {
                 "",
                 "LPAREN",
                 "RPAREN",
                 "IDENTIFIER",
                 "EQUAL",
                 "MULTIPLY",
                 "String",
                 "Integer",
                 "UnlimitedNatural",
                 "Real",
                 "Boolean",
                 "OclAny",
                 "OclVoid",
                 "Invalid",
                 "OclMessage",
                 "MINUS",
                 "GREATER",
                 "LESS",
                 "GREATER_EQUAL",
                 "LESS_EQUAL",
                 "NOT_EQUAL",
                 "Set",
                 "Bag",
                 "Sequence",
                 "Collection",
                 "OrderedSet",
                 "DIVIDE",
                 "and",
                 "or",
                 "xor",
                 "PLUS",
                 "self",
                 "Tuple",
                 "body",
                 "derive",
                 "init",
                 "null",
                 "iterate",
                 "forAll",
                 "exists",
                 "isUnique",
                 "any",
                 "one",
                 "collect",
                 "select",
                 "reject",
                 "collectNested",
                 "sortedBy",
                 "closure",
                 "allInstances",
                 "not",
                 "oclIsKindOf",
                 "oclIsTypeOf",
                 "oclAsType",
                 "oclIsNew",
                 "oclIsUndefined",
                 "oclIsInvalid",
                 "oclIsInState",
                 "STRING_LITERAL",
                 "NUMERIC_OPERATION",
                 "INTEGER_LITERAL",
                 "REAL_LITERAL",
                 "if",
                 "true",
                 "false",
                 "OclInvalid",
                 "new",
                 "let",
                 "ERROR_TOKEN",
                 "COMMA",
                 "TEXT",
                 "BAR",
                 "COLONCOLON",
                 "LBRACE",
                 "LBRACKET",
                 "FOR",
                 "COLON",
                 "NOT_EQUAL_EXEQ",
                 "RBRACKET",
                 "ATPRE",
                 "EXCLAMATION_MARK",
                 "ENDAROUND",
                 "RBRACE",
                 "SEMICOLON",
                 "INTEGER_RANGE_START",
                 "AS",
                 "endif",
                 "in",
                 "ARROW",
                 "DOT",
                 "DOTDOT",
                 "CARET",
                 "CARETCARET",
                 "QUESTIONMARK",
                 "RESET_ASSIGN",
                 "AROUND",
                 "DEFINE",
                 "ENDDEFINE",
                 "SEPARATOR",
                 "FOREACH",
                 "CEND",
                 "ID",
                 "DISABLE",
                 "then",
                 "else",
                 "implies",
                 "EOF_TOKEN",
                 "QUOTE_STRING_LITERAL",
                 "IMPORT",
                 "EXTENSION",
                 "ERROR",
                 "EXPAND",
                 "ITERATOR",
                 "ENDFOREACH",
                 "FILE",
                 "ENDFILE",
                 "IF",
                 "ELSEIF",
                 "ELSE",
                 "ENDIF",
                 "LET",
                 "ENDLET",
                 "PROTECT",
                 "CSTART",
                 "ENDPROTECT",
                 "LG",
                 "xselect",
                 "xcollect",
                 "selectOne",
                 "collectOne",
                 "collectselect",
                 "collectselectOne",
                 "ADD_ASSIGN",
                 "AT_SIGN",
                 "inv",
                 "pre",
                 "post",
                 "context",
                 "package",
                 "endpackage",
                 "def",
                 "attr",
                 "oper",
                 "end",
                 "while",
                 "out",
                 "object",
                 "transformation",
                 "import",
                 "library",
                 "metamodel",
                 "mapping",
                 "query",
                 "helper",
                 "inout",
                 "when",
                 "var",
                 "configuration",
                 "intermediate",
                 "property",
                 "population",
                 "map",
                 "xmap",
                 "late",
                 "log",
                 "assert",
                 "with",
                 "resolve",
                 "resolveone",
                 "resolveIn",
                 "resolveoneIn",
                 "invresolve",
                 "invresolveone",
                 "invresolveIn",
                 "invresolveoneIn",
                 "modeltype",
                 "uses",
                 "where",
                 "refines",
                 "enforcing",
                 "access",
                 "extends",
                 "blackbox",
                 "abstract",
                 "static",
                 "result",
                 "main",
                 "this",
                 "switch",
                 "case",
                 "return",
                 "rename",
                 "disjuncts",
                 "merges",
                 "inherits",
                 "forEach",
                 "forOne",
                 "compute"
             };

    public final static boolean isValidForParser = true;
}
