/*
 * Copyright (c) 2006, 2008 Borland Software Corporation and others.
 * All rights reserved.   This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     committers of openArchitectureWare - Xpand language syntax
 *     Artem Tikhomirov (Borland) - LALR grammar
 *                                - Migration to OCL expressions
 */
package org.eclipse.gmf.internal.xpand.parser;

public interface XpandKWLexersym {
    public final static int
      Char_DollarSign = 47,
      Char_a = 8,
      Char_b = 34,
      Char_c = 10,
      Char_d = 12,
      Char_e = 1,
      Char_f = 21,
      Char_g = 22,
      Char_h = 26,
      Char_i = 6,
      Char_j = 36,
      Char_k = 42,
      Char_l = 4,
      Char_m = 27,
      Char_n = 3,
      Char_o = 9,
      Char_p = 18,
      Char_q = 37,
      Char_r = 7,
      Char_s = 5,
      Char_t = 2,
      Char_u = 14,
      Char_v = 28,
      Char_w = 35,
      Char_x = 38,
      Char_y = 23,
      Char_z = 48,
      Char_A = 19,
      Char_B = 39,
      Char_C = 31,
      Char_D = 24,
      Char_E = 11,
      Char_F = 29,
      Char_G = 49,
      Char_H = 40,
      Char_I = 15,
      Char_J = 50,
      Char_K = 43,
      Char_L = 30,
      Char_M = 41,
      Char_N = 20,
      Char_O = 13,
      Char_P = 32,
      Char_Q = 51,
      Char_R = 16,
      Char_S = 25,
      Char_T = 17,
      Char_U = 33,
      Char_V = 44,
      Char_W = 52,
      Char_X = 45,
      Char_Y = 53,
      Char_Z = 54,
      Char_EOF = 46;

      public final static String orderedTerminalSymbols[] = {
                 "",
                 "e",
                 "t",
                 "n",
                 "l",
                 "s",
                 "i",
                 "r",
                 "a",
                 "o",
                 "c",
                 "E",
                 "d",
                 "O",
                 "u",
                 "I",
                 "R",
                 "T",
                 "p",
                 "A",
                 "N",
                 "f",
                 "g",
                 "y",
                 "D",
                 "S",
                 "h",
                 "m",
                 "v",
                 "F",
                 "L",
                 "C",
                 "P",
                 "U",
                 "b",
                 "w",
                 "j",
                 "q",
                 "x",
                 "B",
                 "H",
                 "M",
                 "k",
                 "K",
                 "V",
                 "X",
                 "EOF",
                 "DollarSign",
                 "z",
                 "G",
                 "J",
                 "Q",
                 "W",
                 "Y",
                 "Z"
             };

    public final static boolean isValidForParser = true;
}
