<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="gmfgraph"
    nsURI="http://www.eclipse.org/gmf/2005/GraphicalDefinition" nsPrefix="gmfgraph">
  <eClassifiers xsi:type="ecore:EClass" name="Canvas" eSuperTypes="#//Identity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="figures" upperBound="-1"
        eType="#//FigureGallery" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//Node" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connections" upperBound="-1"
        eType="#//Connection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="compartments" upperBound="-1"
        eType="#//Compartment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Child" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FigureGallery" eSuperTypes="#//Identity">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Kind of explicit figure library notion. Allows to specify plugin ids (allows importing it later from gmfgen code) in addition to figures"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="figures" upperBound="-1"
        eType="#//Figure" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="implBundles" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Identity" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Easy and readable way to reference element of the model from another one"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiagramElement" abstract="true" eSuperTypes="#//Identity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="figure" lowerBound="1"
        eType="#//Figure"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="facets" upperBound="-1"
        eType="#//VisualFacet" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="anything to further specify constraint or any other aspect of the element"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node" eSuperTypes="#//DiagramElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resizeConstraint" eType="#//Direction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connection" eSuperTypes="#//DiagramElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Compartment" eSuperTypes="#//DiagramElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="collapsible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="needsTitle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Child" eSuperTypes="#//DiagramElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="VisualFacet" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="GeneralFacet" eSuperTypes="#//VisualFacet">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="provide means to attach arbitrary data to your diagram element definition. It's up to you (template author) to process it somehow."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="data" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GradientFacet" eSuperTypes="#//VisualFacet">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="#//Direction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FigureMarker" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Anything you could combine visual representation from. Ordinary GEF figures, custom-defined or references to defined elsewhere."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Figure" interface="true" eSuperTypes="#//FigureMarker #//Identity">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="org.eclipse.draw2d.Figure"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//FigureMarker" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Figure"
        changeable="false" resolveProxies="false" eOpposite="#//Figure/children"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="colorStyle" eType="#//ColorStyle"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sizeStyle" eType="#//SizeStyle"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fontStyle" eType="#//FontStyle"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" eType="#//Point"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="size" eType="#//Point"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="layoutManager" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FigureRef" eSuperTypes="#//FigureMarker">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Need this to facilitate reuse of figures while keeping (so nice looking) containment relationship in the Figure class"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="figure" lowerBound="1"
        eType="#//Figure">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="not FigureMarker because don't want to reference figure references."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectionFigure" interface="true" eSuperTypes="#//Figure"/>
  <eClassifiers xsi:type="ecore:EClass" name="DecorationFigure" interface="true" eSuperTypes="#//Figure"/>
  <eClassifiers xsi:type="ecore:EClass" name="Shape" abstract="true" eSuperTypes="#//Figure">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="org.eclipse.draw2d.Shape"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outline" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fill" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineWidth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineKind" eType="#//LineKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Label" eSuperTypes="#//Figure">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="org.eclipse.draw2d.Label"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LabeledContainer" eSuperTypes="#//Figure">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="org.eclipse.draw2d.LabeledContainer"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rectangle" eSuperTypes="#//Shape">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="org.eclipse.draw2d.RectangleFigure"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoundedRectangle" eSuperTypes="#//Shape">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="org.eclipse.draw2d.RoundedRectangle"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cornerWidth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cornerHeight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ellipse" eSuperTypes="#//Shape">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="org.eclipse.draw2d.Ellipse"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Polyline" eSuperTypes="#//Shape">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="org.eclipse.draw2d.Polyline"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="template" upperBound="-1"
        eType="#//Point" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Polygon" eSuperTypes="#//Polyline">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="org.eclipse.draw2d.Polygon"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PolylineConnection" eSuperTypes="#//Polyline #//ConnectionFigure">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="org.eclipse.draw2d.PolylineConnection"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceDecoration" eType="#//DecorationFigure"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetDecoration" eType="#//DecorationFigure"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PolylineDecoration" eSuperTypes="#//Polyline #//DecorationFigure">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="org.eclipse.draw2d.PolylineDecoration"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PolygonDecoration" eSuperTypes="#//Polygon #//DecorationFigure">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="org.eclipse.draw2d.PolygonDecoration"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CustomFigure" eSuperTypes="#//Figure">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Any figure class provided by some bundle"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifiedClassName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bundleName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CustomDecoration" eSuperTypes="#//CustomFigure #//DecorationFigure">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Same as CustomFigure, but for Decorations"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CustomConnection" eSuperTypes="#//CustomFigure #//ConnectionFigure">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Same as CustomFigure, but for Connections"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColorStyle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="foregroundColor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="backgroundColor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SizeStyle">
    <eStructuralFeatures xsi:type="ecore:EReference" name="maxSize" eType="#//Point"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="minSize" eType="#//Point"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="prefSize" eType="#//Point"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FontStyle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="faceName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Point">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Direction">
    <eLiterals name="NORTH" value="1"/>
    <eLiterals name="SOUTH" value="2"/>
    <eLiterals name="EAST" value="4"/>
    <eLiterals name="WEST" value="8"/>
    <eLiterals name="NORTH_WEST" value="16"/>
    <eLiterals name="NORTH_EAST" value="32"/>
    <eLiterals name="SOUTH_WEST" value="64"/>
    <eLiterals name="SOUTH_EAST" value="128"/>
    <eLiterals name="VERTICAL" value="3"/>
    <eLiterals name="HORIZONTAL" value="12"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LineKind">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="org.eclipse.draw2d.Graphics.LINE_* (== org.eclipse.swt.SWT.LINE_*. Values are same as SWT constants"/>
    </eAnnotations>
    <eLiterals name="LINE_SOLID" value="1"/>
    <eLiterals name="LINE_DASH" value="2"/>
    <eLiterals name="LINE_DOT" value="3"/>
    <eLiterals name="LINE_DASHDOT" value="4"/>
    <eLiterals name="LINE_DASHDOTDOT" value="5"/>
    <eLiterals name="LINE_CUSTOM" value="6"/>
  </eClassifiers>
</ecore:EPackage>
