<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mappings"
    nsURI="http://www.eclipse.org/gmf/2005/mappings" nsPrefix="gmfmap">
  <eClassifiers xsi:type="ecore:EClass" name="AbstractNodeMapping" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2004/EmfaticAnnotationMap">
      <details key="constraints" value="http://www.eclipse.org/gmf/2005/constraints"/>
      <details key="constraintsMeta" value="http://www.eclipse.org/gmf/2005/constraints/meta"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagramNode" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.gmf.diadef/models/diadef.ecore#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainMetaElement" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainSpecialization" eType="#//Constraint"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Specializes further the domain meta element EClass associated with this mapping and should be evaluated in this EClass context"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/gmf/2005/constraints/meta">
        <details key="def" value="context"/>
        <details key="ocl" value="if domainMetaElement.oclIsUndefined() then containmentFeature.eContainingClass else domainMetaElement endif"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainInitializer" eType="#//ElementInitializer"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Initializer for the domain model element associated with mapping"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/gmf/2005/constraints">
        <details key="ocl" value="let i : FeatureSeqInitializer = domainInitializer.oclAsType( FeatureSeqInitializer) in i.oclIsUndefined() or i.initializers.feature.eContainingClass->forAll(c|c.isSuperTypeOf(domainMetaElement))"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/gmf/2005/constraints/meta">
        <details key="def" value="context"/>
        <details key="ocl" value="if domainMetaElement.oclIsUndefined() then containmentFeature.eContainingClass else domainMetaElement endif"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containmentFeature" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EReference">
      <eAnnotations source="http://www.eclipse.org/gmf/2005/constraints">
        <details key="ocl" value="containmentFeature.containment"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/gmf/2005/constraints">
        <details key="ocl" value="domainMetaElement.oclIsUndefined() or containmentFeature.eReferenceType.isSuperTypeOf(domainMetaElement)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="editFeature" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute">
      <eAnnotations source="http://www.eclipse.org/gmf/2005/constraints">
        <details key="ocl" value="editFeature.oclIsUndefined() or (not domainMetaElement.oclIsUndefined() and editFeature.eContainingClass.isSuperTypeOf(domainMetaElement)) or containmentFeature.eType.oclAsType(ecore::EClass).eAllAttributes->includes(editFeature)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childMappings" upperBound="-1"
        eType="#//ChildNodeMapping" containment="true" eOpposite="#//ChildNodeMapping/parentNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MappingEntry" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="NodeMapping" eSuperTypes="#//MappingEntry #//AbstractNodeMapping"/>
  <eClassifiers xsi:type="ecore:EClass" name="ChildNodeMapping" eSuperTypes="#//AbstractNodeMapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="compartment" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.gmf.diadef/models/diadef.ecore#//Compartment">
      <eAnnotations source="http://www.eclipse.org/gmf/2005/constraints">
        <details key="ocl" value="parentNode.diagramNode.oclAsType(diadef::Node).compartments->includes(self.compartment)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentNode" lowerBound="1"
        eType="#//AbstractNodeMapping" changeable="false" eOpposite="#//AbstractNodeMapping/childMappings"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LinkMapping" eSuperTypes="#//MappingEntry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagramLink" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.gmf.diadef/models/diadef.ecore#//Connection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainMetaElement" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainSpecialization" eType="#//Constraint"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Specializes further the domain meta element EClass associated with this mapping and should be evaluated in this EClass context"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/gmf/2005/constraints/meta">
        <details key="def" value="context"/>
        <details key="ocl" value="if domainMetaElement.oclIsUndefined() then linkMetaFeature.eContainingClass else domainMetaElement endif "/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainInitializer" eType="#//ElementInitializer"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Initializer for the domain model element associated with mapping"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/gmf/2005/constraints">
        <details key="ocl" value="let i : FeatureSeqInitializer = domainInitializer.oclAsType( FeatureSeqInitializer) in i.oclIsUndefined() or i.initializers.feature.eContainingClass->forAll(c|c.isSuperTypeOf(domainMetaElement)) "/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/gmf/2005/constraints/meta">
        <details key="def" value="context"/>
        <details key="ocl" value="if domainMetaElement.oclIsUndefined() then linkMetaFeature.eContainingClass else domainMetaElement endif "/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containmentFeature" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EReference">
      <eAnnotations source="http://www.eclipse.org/gmf/2005/constraints">
        <details key="ocl" value="containmentFeature.oclIsUndefined() or containmentFeature.eReferenceType.isSuperTypeOf(domainMetaElement)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="labelEditFeature" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute">
      <eAnnotations source="http://www.eclipse.org/gmf/2005/constraints">
        <details key="ocl" value="labelEditFeature.oclIsUndefined() or labelEditFeature.eContainingClass.isSuperTypeOf(domainMetaElement)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="labelDisplayFeature" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="By default, same as editFeature, once latter is set"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/gmf/2005/constraints">
        <details key="ocl" value="labelDisplayFeature.oclIsUndefined() or labelDisplayFeature.eContainingClass.isSuperTypeOf(domainMetaElement)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkMetaFeature" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature">
      <eAnnotations source="http://www.eclipse.org/gmf/2005/constraints">
        <details key="ocl" value="domainMetaElement.oclIsUndefined() or linkMetaFeature.eContainingClass.isSuperTypeOf(domainMetaElement)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="creationConstraints" eType="#//LinkConstraints"
        containment="true" eOpposite="#//LinkConstraints/linkMapping">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Specifies additional restrictions on link creation"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CanvasMapping" eSuperTypes="#//MappingEntry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagramCanvas" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.gmf.diadef/models/diadef.ecore#//Canvas"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainModel" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EPackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainMetaElement" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" lowerBound="1" upperBound="-1"
        eType="#//NodeMapping" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
        eType="#//LinkMapping" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagram" lowerBound="1"
        eType="#//CanvasMapping" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint" eSuperTypes="#//ValueExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Boolean type value expression which is to be evaluated in a context"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/gmf/2005/constraints/meta">
      <details key="def" value="Constraint"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LinkConstraints">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Groups constraints on the link source and target end"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkMapping" lowerBound="1"
        eType="#//LinkMapping" changeable="false" eOpposite="#//LinkMapping/creationConstraints">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="References the link mapping restricted by these constraints"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceEnd" eType="#//Constraint"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Restriction enforced by the the source end, may reference variables 'oppositeEnd' pointing to targetEnd and 'link' denoting the link domainmetaElement instance if available."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetEnd" eType="#//Constraint"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Restriction enforced by the the target end, may reference variables 'oppositeEnd' pointing to sourceEnd and 'link' denoting the link domainmetaElement instance if available."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueExpression">
    <eAnnotations source="http://www.eclipse.org/gmf/2005/constraints/meta">
      <details key="def" value="ValueSpec"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Expression as a textual statement which results in a value when evaluated in a context"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="body" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The text of the expression"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/gmf/2005/constraints/meta">
        <details key="def" value="body"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="ocl">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Specifies the language in which the expression is stated"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/gmf/2005/constraints/meta">
        <details key="def" value="lang"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElementInitializer" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Base class for initializers of domain model elements"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureSeqInitializer" eSuperTypes="#//ElementInitializer">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Feature sequence initializer"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initializers" lowerBound="1"
        upperBound="-1" eType="#//FeatureValueSpec" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Value specifications as initializers for individual features which should be initialized in the order given by this list"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureValueSpec" eSuperTypes="#//ValueExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Value specification associated with a specific feature"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/gmf/2005/constraints/meta">
      <details key="def" value="ValueSpec"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Denotes the feature for which this value expression is specified. Its containing EClass is the context for evaluation."/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/gmf/2005/constraints/meta">
        <details key="def" value="type"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
